apiVersion: batch/v1
kind: Job
metadata:
  name: inital_job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: print
        image: busybox:stable
        command: ["echo","Hello World"]
      restartPolicy: Never
  backoffLimit: 4
  activeDeadlineSeconds: 10

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron_job
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
        backoffLimit: 4
        activeDeadlineSeconds: 10
