---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  selector:
    app: jenkins-server
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: jenkins
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: jenkins-service
      port:
        number: 8080

# Using Kustomize we can make the following fields dynamic:
# - name: jenkins-pv-volume and namespace: jenkins
#   port: 8080 and targetPort: 8080
#   name: for both ingress and service