apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  namespace: sonarqube
  labels:
    app: postgres
data:
  POSTGRES_DB: sonarqube
  POSTGRES_USER: sonarqube
  POSTGRES_PASSWORD: mypassword
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-configmap
  namespace: sonarqube
  labels:
    app: postgres
data:
  SONAR_JDBC_URL: jdbc://100.64.30.217:31111/sonarqube
  SONAR_JDBC_USERNAME: sonarqube
  SONAR_JDBC_PASSWORD: mypassword