
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-deployment
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: sonarqube
            - name: POSTGRES_PASSWORD
              value: mypassword
            - name: POSTGRES_DB
              value: sonarqube
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
      volumes:
        - name: postgres-pv-volume
          persistentVolumeClaim:
            claimName: postgres-pvc