---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  labels:
    type: local
spec:
  storageClassName: gp2
  claimRef:
    name: postgres-pvc
    namespace: sonarqube
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-100-64-9-97.eu-west-1.compute.internal
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-pv-volume
  labels:
    type: local
spec:
  storageClassName: gp2
  claimRef:
    name: sonarqube-pv-claim
    namespace: sonarqube
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-100-64-19-63.eu-west-1.compute.internal
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-pv-claim
  namespace: sonarqube
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi